HyperJob Agency/HyperJob Agency/task/hyperjob/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from .views import index, SignUpView, Login, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('home', HomeView.as_view(), name='home'),
    path('home/', RedirectView.as_view(url='/home')),
    path('', include('resume.urls')),
    path('', include('vacancy.urls')),
    path('login', Login.as_view()),
    path('signup', SignUpView.as_view()),
    path('signup/', RedirectView.as_view(url='/signup')),
    path('login/', RedirectView.as_view(url="/login"))

]

HyperJob Agency/HyperJob Agency/task/resume/urls.py
from django.urls import path
from django.views.generic import RedirectView
from .views import ResumeView, CreateResume

app_name = "resume"

urlpatterns = [
    path('resumes', ResumeView.as_view(), name="resume"),
    path('resume/new/', RedirectView.as_view(url='resume/new')),
    path('resume/new', CreateResume.as_view(), name="new")
]

HyperJob Agency/HyperJob Agency/task/vacancy/urls.py
from django.urls import path
from .views import VacancyView, CreateVacancy
from django.views.generic import RedirectView

app_name = "vacancy"
urlpatterns = [
    path('vacancies', VacancyView.as_view(), name="main"),
    path('vacancy/new/', RedirectView.as_view(url="/new")),
    path('vacancy/new', CreateVacancy.as_view(), name="new")
]

HyperJob Agency/HyperJob Agency/task/resume/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Resume(models.Model):
    description = models.TextField(max_length=1024)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

HyperJob Agency/HyperJob Agency/task/vacancy/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Vacancy(models.Model):
    description = models.TextField(max_length=1024)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

HyperJob Agency/HyperJob Agency/task/resume/forms.py
from django import forms


class ResumeForm(forms.Form):
    description = forms.CharField(label="Description")


class VacancyForm(forms.Form):
    description = forms.CharField(label="Description")

HyperJob Agency/HyperJob Agency/task/hyperjob/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.views.generic import CreateView, View
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import RedirectView
from django.contrib.auth.models import User
from resume.forms import ResumeForm, VacancyForm


def index(request):
    return render(request, "hyperjob/index.html")


class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        if request.user.is_staff:
            vacancy_form = VacancyForm()
            context['postcard_form'] = vacancy_form
            context['type'] = 'vacancy'
        else:
            resume_form = ResumeForm()
            context['postcard_form'] = resume_form
            context['type'] = 'resume'
        return render(request, template_name='form.html', context=context)


class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = 'hyperjob/signup.html'
    success_url = 'login'


class Login(LoginView):
    form_class = AuthenticationForm
    redirect_authenticated_user = True
    template_name = 'hyperjob/login.html'

HyperJob Agency/HyperJob Agency/task/resume/views.py
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from .models import Resume
from django.core.exceptions import PermissionDenied
from .forms import ResumeForm


# Create your views here.
class ResumeView(View):
    def get(self, request, *args, **kwargs):
        values = Resume.objects.all()
        context = {"resumes": values}
        return render(request, context=context, template_name='resume/resume.html')


class CreateResume(View):

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied

        resume_form = ResumeForm(request.POST)
        if resume_form.is_valid():
            print(resume_form.cleaned_data['description'])
            user = request.user
            resume = Resume(description=resume_form.cleaned_data['description'], author=user)
            resume.save()
            return redirect('/home')
        else:
            raise PermissionDenied

HyperJob Agency/HyperJob Agency/task/vacancy/views.py
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect

from django.views import View
from .models import Vacancy
from resume.forms import VacancyForm


# Create your views here.
class VacancyView(View):
    def get(self, request, *args, **kwargs):
        values = Vacancy.objects.all()
        context = {"vacancies": values}
        return render(request, context=context, template_name='vacancy/vacancy.html')


class CreateVacancy(View):

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied
        if not request.user.is_staff:
            raise PermissionDenied

        vacancy_form = VacancyForm(request.POST)
        if vacancy_form.is_valid():
            user = request.user
            resume = Vacancy(description=vacancy_form.cleaned_data['description'], author=user)
            resume.save()
            return redirect('/home')
        else:
            raise PermissionDenied

HyperJob Agency/HyperJob Agency/task/resume/templates/resume/resume.html
{% extends "base_view.html"%}
{%block title%}Resume{%endblock%}
{% block content%}
 {%for resume in resumes %}
<div>{{resume.author.username}}: {{resume.description}}</div>
{%endfor%}
{%endblock%}

HyperJob Agency/HyperJob Agency/task/templates/base_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}</title>
</head>
<body>
{%block content%}
{% endblock %}
</body>
</html>

HyperJob Agency/HyperJob Agency/task/templates/form.html
{% extends "base_view.html"%}
{%block title%}New Resume{%endblock%}
{% block content%}
<h1>{{type}}</h1>

<form method="post"
      action="{{type}}/new">
    {% csrf_token %}
  <table>{{ postcard_form.as_table }}</table>
  <button type="submit">Submit</button>
</form>
{%endblock%}

HyperJob Agency/HyperJob Agency/task/templates/hyperjob/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ruslan</title>
</head>
<body>
<h2>Welcome to HyperJob!</h2>

<div>
    <ul>
        <li> <a href="/login">Login page</a></li>
        <li><a href="/signup">Sign up page</a></li>
        <li> <a href="{%url 'vacancy:main'%}">Vacancy list</a></li>
        <li><a href="{%url 'resume:resume'%}">Resume list</a></li>
        <li><a href="/home">Home list</a></li>
    </ul>
</div>
</body>
</html>

HyperJob Agency/HyperJob Agency/task/templates/hyperjob/login.html
{% extends 'base_view.html' %}
{%block content%}
<form method="post" action="login">
  {% csrf_token %}
  <table>{{ form.as_table }}</table>
  <button type="submit">Login</button>
</form>
{%endblock%}}

HyperJob Agency/HyperJob Agency/task/templates/hyperjob/signup.html
{% extends 'base_view.html' %}
{%block content%}
<form method="post" action="signup">
  {% csrf_token %}
  <table>{{ form.as_table }}</table>
  <button type="submit">Send</button>
</form>
{%endblock%}

HyperJob Agency/HyperJob Agency/task/vacancy/templates/vacancy/vacancy.html
{% extends "base_view.html"%}
{%block title%}Vacancy{%endblock%}
{% block content%}
 {%for vacancy in vacancies %}
<div>{{vacancy.author.username}}: {{vacancy.description}}</div>
{%endfor%}
{%endblock%}